#!/bin/bash

#2016. aastal valiti Eesti presidendiks Kersti Kaljulaid

aasta=2016

president="Kersti Kaljulaid"

lause_keskosa=". aastal valiti Eesti presidendiks "

lause="$aasta$lause_keskosa$president"

echo $lause

