#!/bin/bash

#skript bussiekskursioonide korraldajale
# mitu reisijat ja kohtade arv, tulemuseks täidetud busside arv ja mitu maas

read -p "Sisestage reisijate arv grupis: " reisijad
read -p "Sisestage kohtade arv ühes bussis: " kohad

taidetud_bussid=$((reisijad / kohad))
maha_jaanud=$((reisijad % kohad))

echo "Täielikult täidetud busse: $taidetud_bussid"
echo "Maha jäänud inimesi: $maha_jaanud"

if test $maha_jaanud -gt 0
then
	taidetud_bussid=$(($taidetud_bussid + 1))
fi

echo "Kokku on vaja $taidetud_bussid taisbussi"
