#!/bin/bash

#Kasutaja sisestab kellaaja ja skript tervitab vastavalt ajale

kasutajanimi=$(whoami)

echo -e "Sisesta aja vaartus: \c"
read aeg

if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
	echo "Tere hommikust, $kasutajanimi !"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	echo "Tere paevast, $kasutajanimi !"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	echo "Tere ohtust, $kasutajanimi !"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
	echo "Head ood, $kasutajanimi !"
else
	echo "Vale sisend!"
fi
