#!/bin/bash

#väljastan arvu, kas arv on paaris või mitte?

read -p "Sisesta suvaline täisarv: " arv

jaak=$(( $arv % 2 ))
if [ $jaak -eq 0 ]
then
    echo "$arv on paarisarv."
else
    echo "$arv on paaritu."
fi

